#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$PATH:/usr/lib/jvm/java-8-oracle/bin/

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="/home/boris/.sdkman"
#[[ -s "/home/boris/.sdkman/bin/sdkman-init.sh" ]] && source "/home/boris/.sdkman/bin/sdkman-init.sh"

export GRAILS_ENV=dev
export POSTGRES_TCP_ADDR=localhost
export DB_USERNAME=backoffice
export DB_PASSWORD=admin
export ACTIVEMQ_URL=tcp://localhost:61616
export ACTIVEMQ_USERNAME=admin
export ACTIVEMQ_PASSWORD=admin
export export PATH=$PATH:/home/boris/applications/bin
